load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "serverless",
    srcs = [
        "labels.go",
        "memory.go",
        "pd_config.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/util/serverless",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/metrics",
        "//pkg/util/gctuner",
        "//pkg/util/logutil",
        "//pkg/util/memory",
        "@com_github_tikv_pd_client//:client",
        "@org_uber_go_zap//:zap",
    ],
)
