// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/executor/spfresh/spfreshpb/vector_search.proto

package spfreshpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ColumnInfo is wire-compatible with tipb.ColumnInfo.
// IMPORTANT: field numbers must not change.
type ColumnInfo struct {
	ColumnId             int64    `protobuf:"varint,1,opt,name=column_id,json=columnId,proto3" json:"column_id,omitempty"`
	Tp                   int32    `protobuf:"varint,2,opt,name=tp,proto3" json:"tp,omitempty"`
	Collation            int32    `protobuf:"varint,3,opt,name=collation,proto3" json:"collation,omitempty"`
	ColumnLen            int32    `protobuf:"varint,4,opt,name=columnLen,proto3" json:"columnLen,omitempty"`
	Decimal              int32    `protobuf:"varint,5,opt,name=decimal,proto3" json:"decimal,omitempty"`
	Flag                 int32    `protobuf:"varint,6,opt,name=flag,proto3" json:"flag,omitempty"`
	Elems                []string `protobuf:"bytes,7,rep,name=elems,proto3" json:"elems,omitempty"`
	DefaultVal           []byte   `protobuf:"bytes,8,opt,name=default_val,json=defaultVal,proto3" json:"default_val,omitempty"`
	PkHandle             bool     `protobuf:"varint,21,opt,name=pk_handle,json=pkHandle,proto3" json:"pk_handle,omitempty"`
	Array                bool     `protobuf:"varint,22,opt,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnInfo) Reset()         { *m = ColumnInfo{} }
func (m *ColumnInfo) String() string { return proto.CompactTextString(m) }
func (*ColumnInfo) ProtoMessage()    {}
func (*ColumnInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2babf5c62f0513d5, []int{0}
}
func (m *ColumnInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnInfo.Unmarshal(m, b)
}
func (m *ColumnInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnInfo.Marshal(b, m, deterministic)
}
func (m *ColumnInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnInfo.Merge(m, src)
}
func (m *ColumnInfo) XXX_Size() int {
	return xxx_messageInfo_ColumnInfo.Size(m)
}
func (m *ColumnInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnInfo proto.InternalMessageInfo

type VectorSearchRequest struct {
	KeyspaceId uint32 `protobuf:"varint,1,opt,name=keyspace_id,json=keyspaceId,proto3" json:"keyspace_id,omitempty"`
	TableId    int64  `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	IndexId    int64  `protobuf:"varint,3,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	StartTs    uint64 `protobuf:"varint,4,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	TopK       uint32 `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// query_vector_f32_le is f32 little-endian bytes, without the dims prefix.
	QueryVectorF32Le []byte        `protobuf:"bytes,6,opt,name=query_vector_f32_le,json=queryVectorF32Le,proto3" json:"query_vector_f32_le,omitempty"`
	RequiredColumns  []*ColumnInfo `protobuf:"bytes,7,rep,name=required_columns,json=requiredColumns,proto3" json:"required_columns,omitempty"`
	// Optional tuning/debug parameters.
	MaxBatches           uint32   `protobuf:"varint,8,opt,name=max_batches,json=maxBatches,proto3" json:"max_batches,omitempty"`
	OversampleFactor     uint32   `protobuf:"varint,9,opt,name=oversample_factor,json=oversampleFactor,proto3" json:"oversample_factor,omitempty"`
	Debug                bool     `protobuf:"varint,10,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VectorSearchRequest) Reset()         { *m = VectorSearchRequest{} }
func (m *VectorSearchRequest) String() string { return proto.CompactTextString(m) }
func (*VectorSearchRequest) ProtoMessage()    {}
func (*VectorSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2babf5c62f0513d5, []int{1}
}
func (m *VectorSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorSearchRequest.Unmarshal(m, b)
}
func (m *VectorSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorSearchRequest.Marshal(b, m, deterministic)
}
func (m *VectorSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorSearchRequest.Merge(m, src)
}
func (m *VectorSearchRequest) XXX_Size() int {
	return xxx_messageInfo_VectorSearchRequest.Size(m)
}
func (m *VectorSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VectorSearchRequest proto.InternalMessageInfo

type VectorSearchResponse struct {
	Rows                 []*VectorSearchRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Stats                *VectorSearchStats `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VectorSearchResponse) Reset()         { *m = VectorSearchResponse{} }
func (m *VectorSearchResponse) String() string { return proto.CompactTextString(m) }
func (*VectorSearchResponse) ProtoMessage()    {}
func (*VectorSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2babf5c62f0513d5, []int{2}
}
func (m *VectorSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorSearchResponse.Unmarshal(m, b)
}
func (m *VectorSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorSearchResponse.Marshal(b, m, deterministic)
}
func (m *VectorSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorSearchResponse.Merge(m, src)
}
func (m *VectorSearchResponse) XXX_Size() int {
	return xxx_messageInfo_VectorSearchResponse.Size(m)
}
func (m *VectorSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VectorSearchResponse proto.InternalMessageInfo

type VectorSearchRow struct {
	HandleBytes          []byte   `protobuf:"bytes,1,opt,name=handle_bytes,json=handleBytes,proto3" json:"handle_bytes,omitempty"`
	Distance             float32  `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	ColumnValues         [][]byte `protobuf:"bytes,3,rep,name=column_values,json=columnValues,proto3" json:"column_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VectorSearchRow) Reset()         { *m = VectorSearchRow{} }
func (m *VectorSearchRow) String() string { return proto.CompactTextString(m) }
func (*VectorSearchRow) ProtoMessage()    {}
func (*VectorSearchRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_2babf5c62f0513d5, []int{3}
}
func (m *VectorSearchRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorSearchRow.Unmarshal(m, b)
}
func (m *VectorSearchRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorSearchRow.Marshal(b, m, deterministic)
}
func (m *VectorSearchRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorSearchRow.Merge(m, src)
}
func (m *VectorSearchRow) XXX_Size() int {
	return xxx_messageInfo_VectorSearchRow.Size(m)
}
func (m *VectorSearchRow) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorSearchRow.DiscardUnknown(m)
}

var xxx_messageInfo_VectorSearchRow proto.InternalMessageInfo

type VectorSearchStats struct {
	PartitionsScanned    uint64   `protobuf:"varint,1,opt,name=partitions_scanned,json=partitionsScanned,proto3" json:"partitions_scanned,omitempty"`
	VectorsScanned       uint64   `protobuf:"varint,2,opt,name=vectors_scanned,json=vectorsScanned,proto3" json:"vectors_scanned,omitempty"`
	TableLookupKeys      uint64   `protobuf:"varint,3,opt,name=table_lookup_keys,json=tableLookupKeys,proto3" json:"table_lookup_keys,omitempty"`
	TableLookupBytes     uint64   `protobuf:"varint,4,opt,name=table_lookup_bytes,json=tableLookupBytes,proto3" json:"table_lookup_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VectorSearchStats) Reset()         { *m = VectorSearchStats{} }
func (m *VectorSearchStats) String() string { return proto.CompactTextString(m) }
func (*VectorSearchStats) ProtoMessage()    {}
func (*VectorSearchStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_2babf5c62f0513d5, []int{4}
}
func (m *VectorSearchStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorSearchStats.Unmarshal(m, b)
}
func (m *VectorSearchStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorSearchStats.Marshal(b, m, deterministic)
}
func (m *VectorSearchStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorSearchStats.Merge(m, src)
}
func (m *VectorSearchStats) XXX_Size() int {
	return xxx_messageInfo_VectorSearchStats.Size(m)
}
func (m *VectorSearchStats) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorSearchStats.DiscardUnknown(m)
}

var xxx_messageInfo_VectorSearchStats proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ColumnInfo)(nil), "ColumnInfo")
	proto.RegisterType((*VectorSearchRequest)(nil), "VectorSearchRequest")
	proto.RegisterType((*VectorSearchResponse)(nil), "VectorSearchResponse")
	proto.RegisterType((*VectorSearchRow)(nil), "VectorSearchRow")
	proto.RegisterType((*VectorSearchStats)(nil), "VectorSearchStats")
}

func init() {
	proto.RegisterFile("pkg/executor/spfresh/spfreshpb/vector_search.proto", fileDescriptor_2babf5c62f0513d5)
}

var fileDescriptor_2babf5c62f0513d5 = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x94, 0xd1, 0x8e, 0xd2, 0x40,
	0x14, 0x86, 0xa5, 0xc0, 0x02, 0x07, 0x58, 0x60, 0x76, 0x35, 0x75, 0x35, 0x8a, 0x68, 0x22, 0x51,
	0x17, 0x22, 0x18, 0xaf, 0xcd, 0x9a, 0x6c, 0xdc, 0xec, 0x5e, 0xcd, 0x9a, 0xbd, 0xf0, 0xa6, 0x99,
	0xb6, 0xa7, 0xd0, 0xd0, 0x76, 0xba, 0x9d, 0x29, 0x0b, 0x0f, 0xe1, 0x63, 0x99, 0xf8, 0x1a, 0x5e,
	0xf9, 0x1a, 0xa6, 0x67, 0x60, 0x11, 0xbd, 0xa2, 0xff, 0xf7, 0xff, 0x74, 0xa6, 0xff, 0x9c, 0x16,
	0x26, 0xe9, 0x62, 0x36, 0xc6, 0x15, 0x7a, 0xb9, 0x96, 0xd9, 0x58, 0xa5, 0x41, 0x86, 0x6a, 0xbe,
	0xfd, 0x4d, 0xdd, 0xf1, 0x12, 0x3d, 0x2d, 0x33, 0x47, 0xa1, 0xc8, 0xbc, 0xf9, 0x28, 0xcd, 0xa4,
	0x96, 0x27, 0x1f, 0x66, 0xa1, 0x9e, 0xe7, 0xee, 0xc8, 0x93, 0xf1, 0x78, 0x26, 0x67, 0x72, 0x4c,
	0xd8, 0xcd, 0x83, 0x4f, 0xcb, 0xf7, 0xa3, 0xe9, 0x68, 0x42, 0x90, 0x18, 0x5d, 0x99, 0x7f, 0x0d,
	0xbe, 0x5b, 0x00, 0x9f, 0x65, 0x94, 0xc7, 0xc9, 0x45, 0x12, 0x48, 0xf6, 0x04, 0x1a, 0x1e, 0x29,
	0x27, 0xf4, 0xed, 0x52, 0xbf, 0x34, 0x2c, 0xf3, 0xba, 0x01, 0x17, 0x3e, 0x3b, 0x04, 0x4b, 0xa7,
	0xb6, 0xd5, 0x2f, 0x0d, 0xab, 0xdc, 0xd2, 0x29, 0x7b, 0x4a, 0xe1, 0x48, 0xe8, 0x50, 0x26, 0x76,
	0x99, 0xf0, 0x0e, 0x6c, 0xdc, 0x3c, 0x4e, 0xae, 0x30, 0xb1, 0x2b, 0xf7, 0xae, 0x01, 0xcc, 0x86,
	0x9a, 0x8f, 0x5e, 0x18, 0x8b, 0xc8, 0xae, 0x92, 0xb7, 0x95, 0x8c, 0x41, 0x25, 0x88, 0xc4, 0xcc,
	0x3e, 0x20, 0x4c, 0xd7, 0xec, 0x18, 0xaa, 0x18, 0x61, 0xac, 0xec, 0x5a, 0xbf, 0x3c, 0x6c, 0x70,
	0x23, 0xd8, 0x73, 0x68, 0xfa, 0x18, 0x88, 0x3c, 0xd2, 0xce, 0x52, 0x44, 0x76, 0xbd, 0x5f, 0x1a,
	0xb6, 0x38, 0x6c, 0xd0, 0x8d, 0x88, 0x8a, 0xa7, 0x49, 0x17, 0xce, 0x5c, 0x24, 0x7e, 0x84, 0xf6,
	0xc3, 0x7e, 0x69, 0x58, 0xe7, 0xf5, 0x74, 0xf1, 0x85, 0x74, 0x71, 0x4f, 0x91, 0x65, 0x62, 0x6d,
	0x3f, 0x22, 0xc3, 0x88, 0xc1, 0x6f, 0x0b, 0x8e, 0x6e, 0xa8, 0xdd, 0x6b, 0x2a, 0x97, 0xe3, 0x6d,
	0x8e, 0x4a, 0x17, 0x6b, 0x2d, 0x70, 0xad, 0x52, 0xe1, 0xe1, 0xb6, 0x9a, 0x36, 0x87, 0x2d, 0xba,
	0xf0, 0xd9, 0x63, 0xa8, 0x6b, 0xe1, 0x46, 0xe4, 0x5a, 0x54, 0x5c, 0x8d, 0xb4, 0xb1, 0xc2, 0xc4,
	0xc7, 0x55, 0x61, 0x95, 0x8d, 0x45, 0xda, 0x58, 0x4a, 0x8b, 0x4c, 0x3b, 0x5a, 0x51, 0x47, 0x15,
	0x5e, 0x23, 0xfd, 0x55, 0xb1, 0x23, 0xa8, 0x6a, 0x99, 0x3a, 0x0b, 0xea, 0xa7, 0xcd, 0x2b, 0x5a,
	0xa6, 0x97, 0xec, 0x14, 0x8e, 0x6e, 0x73, 0xcc, 0xd6, 0xce, 0x66, 0x02, 0x82, 0xe9, 0xc4, 0x89,
	0x90, 0xba, 0x6a, 0xf1, 0x2e, 0x59, 0x66, 0xf7, 0xe7, 0xd3, 0xc9, 0x15, 0xb2, 0x8f, 0xd0, 0xcd,
	0xf0, 0x36, 0x0f, 0x33, 0xf4, 0x1d, 0xd3, 0xbd, 0xa9, 0xb0, 0x39, 0x69, 0x8e, 0x76, 0xa7, 0xce,
	0x3b, 0xdb, 0x90, 0x61, 0xd4, 0x6c, 0x2c, 0x56, 0x8e, 0x2b, 0xb4, 0x37, 0x47, 0x45, 0xcd, 0xb6,
	0x39, 0xc4, 0x62, 0x75, 0x66, 0x08, 0x7b, 0x0b, 0x3d, 0xb9, 0xc4, 0x4c, 0x89, 0x38, 0x8d, 0xd0,
	0x09, 0x44, 0xb1, 0xa4, 0xdd, 0xa0, 0x58, 0x77, 0x67, 0x9c, 0x13, 0x2f, 0x9a, 0xf6, 0xd1, 0xcd,
	0x67, 0x36, 0x98, 0xa6, 0x49, 0x0c, 0x02, 0x38, 0xde, 0x2f, 0x5a, 0xa5, 0x32, 0x51, 0xc8, 0x5e,
	0x41, 0x25, 0x93, 0x77, 0xca, 0x2e, 0xd1, 0x3e, 0xbb, 0xa3, 0xbd, 0x90, 0xbc, 0xe3, 0xe4, 0xb2,
	0x21, 0x54, 0x95, 0x16, 0x5a, 0x51, 0xd7, 0xcd, 0x09, 0xdb, 0x8b, 0x5d, 0x17, 0x0e, 0x37, 0x81,
	0x41, 0x0e, 0x9d, 0x7f, 0x6e, 0xc1, 0x5e, 0x40, 0xcb, 0x0c, 0x85, 0xe3, 0xae, 0x35, 0x2a, 0x3a,
	0xcd, 0x16, 0x6f, 0x1a, 0x76, 0x56, 0x20, 0x76, 0x02, 0x75, 0x3f, 0x54, 0x5a, 0x24, 0x1e, 0xd2,
	0x12, 0x16, 0xbf, 0xd7, 0xec, 0x25, 0xb4, 0x37, 0x2f, 0xc9, 0x52, 0x44, 0x39, 0x2a, 0xbb, 0xdc,
	0x2f, 0x0f, 0x5b, 0xbc, 0x65, 0xe0, 0x0d, 0xb1, 0xc1, 0x8f, 0x12, 0xf4, 0xfe, 0xdb, 0x13, 0x3b,
	0x05, 0x96, 0x8a, 0x4c, 0x87, 0xc5, 0x1b, 0xa2, 0x1c, 0xe5, 0x89, 0x24, 0x41, 0x33, 0x4d, 0x15,
	0xde, 0xdb, 0x39, 0xd7, 0xc6, 0x60, 0xaf, 0xa1, 0x63, 0x0e, 0x7a, 0x97, 0xb5, 0x28, 0x7b, 0xb8,
	0xc1, 0xdb, 0xe0, 0x1b, 0xe8, 0x99, 0xe9, 0x8b, 0xa4, 0x5c, 0xe4, 0xa9, 0x53, 0x0c, 0x26, 0xcd,
	0x5a, 0x85, 0x77, 0xc8, 0xb8, 0x22, 0x7e, 0x89, 0x6b, 0xc5, 0xde, 0x01, 0xdb, 0xcb, 0x9a, 0x0e,
	0xcc, 0xf4, 0x75, 0xff, 0x0a, 0x53, 0x11, 0x67, 0x9d, 0x9f, 0xbf, 0x9e, 0x3d, 0xf8, 0xd6, 0xb8,
	0xff, 0xf6, 0xb8, 0x07, 0xf4, 0xe1, 0x98, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xca, 0x59, 0xf1,
	0x5b, 0xa4, 0x04, 0x00, 0x00,
}
