load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "remote",
    srcs = [
        "chunk.go",
        "chunk_sender.go",
        "remote.go",
        "util.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/lightning/backend/remote",
    visibility = ["//visibility:public"],
    deps = [
        "//br/pkg/pdutil",
        "//pkg/lightning/backend",
        "//pkg/lightning/backend/encode",
        "//pkg/lightning/backend/kv",
        "//pkg/lightning/backend/local",
        "//pkg/lightning/checkpoints",
        "//pkg/lightning/common",
        "//pkg/lightning/config",
        "//pkg/lightning/errormanager",
        "//pkg/lightning/log",
        "//pkg/lightning/metric",
        "@com_github_cockroachdb_pebble//:pebble",
        "@com_github_google_uuid//:uuid",
        "@com_github_pingcap_errors//:errors",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_tikv_client_go_v2//oracle",
        "@com_github_tikv_client_go_v2//tikv",
        "@org_uber_go_zap//:zap",
    ],
)
