load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "audit",
    srcs = [
        "entry.go",
        "filter.go",
        "logger.go",
        "manager.go",
        "register.go",
        "util.go",
    ],
    importpath = "github.com/pingcap/tidb/pkg/extension/serverless/audit",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/config",
        "//pkg/extension",
        "//pkg/keyspace",
        "//pkg/kv",
        "//pkg/metrics",
        "//pkg/parser/ast",
        "//pkg/parser/auth",
        "//pkg/parser/mysql",
        "//pkg/parser/terror",
        "//pkg/sessionctx/stmtctx",
        "//pkg/sessionctx/variable",
        "//pkg/types",
        "//pkg/util/chunk",
        "//pkg/util/encrypt",
        "//pkg/util/logutil",
        "//pkg/util/sqlexec",
        "//pkg/util/stringutil",
        "//pkg/util/table-filter",
        "@com_github_google_uuid//:uuid",
        "@com_github_ngaut_pools//:pools",
        "@com_github_pingcap_errors//:errors",
        "@com_github_pingcap_log//:log",
        "@in_gopkg_natefinch_lumberjack_v2//:lumberjack_v2",
        "@io_etcd_go_etcd_api_v3//mvccpb",
        "@io_etcd_go_etcd_client_v3//:client",
        "@org_uber_go_atomic//:atomic",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zapcore",
    ],
)

go_test(
    name = "audit_test",
    timeout = "short",
    srcs = [
        "entry_test.go",
        "filter_test.go",
        "function_test.go",
        "sysvar_test.go",
    ],
    embed = [":audit"],
    flaky = True,
    shard_count = 21,
    deps = [
        "//pkg/config",
        "//pkg/errno",
        "//pkg/parser",
        "//pkg/parser/auth",
        "//pkg/server",
        "//pkg/sessionctx/stmtctx",
        "//pkg/testkit",
        "//pkg/util/sem",
        "@com_github_pingcap_errors//:errors",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_zap//:zap",
    ],
)
