name: Tests

on:
  pull_request:
    branches:
      - main-8.5-keyspace
      - release-8.5-keyspace*
    types: [opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-part-1:
    runs-on: [X64, gcp]
    if: contains(github.event.pull_request.labels.*.name, 'run-ut')
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
      GOPRIVATE: github.com/tidbcloud
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false # Use our own cache directly for more effective caching
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: Load Go module cache
        uses: breezewish/gcs-cache/restore@017eacc3417cc8c77f2e7ca1f92cc1be5d54ac1e
        with:
          gcs-bucket: pingcap-dbaas-build_cloudbuild
          path: |
            ~/go/pkg/mod
          key: tidb-cse/ci-build/mod/${{ runner.os }}-${{ runner.arch }}/${{ github.ref_name }}/${{ hashFiles('./go.sum') }}
          restore-keys: |
            tidb-cse/ci-build/mod/${{ runner.os }}-${{ runner.arch }}/${{ github.ref_name }}
            tidb-cse/daily/mod/${{ runner.os }}-${{ runner.arch }}/main-8.5-keyspace/${{ hashFiles('./go.sum') }}
            tidb-cse/daily/mod/${{ runner.os }}-${{ runner.arch }}/main-8.5-keyspace

      - name: Load Go build cache
        uses: breezewish/gcs-cache/restore@017eacc3417cc8c77f2e7ca1f92cc1be5d54ac1e
        with:
          gcs-bucket: pingcap-dbaas-build_cloudbuild
          path: |
            ~/.cache/go-build
          key: tidb-cse/ci-build/build/${{ runner.os }}-${{ runner.arch }}/${{ github.ref_name }}
          restore-keys: |
            tidb-cse/daily/build/${{ runner.os }}-${{ runner.arch }}/main-8.5-keyspace

      - name: make test_part_1
        shell: bash
        run: |
          make test_part_1

      - name: Upload log on error
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test.out
          path: ${{ runner.temp }}/tests/integrationtest/integration-test.out

  test-part-2:
    runs-on: [X64, gcp]
    if: contains(github.event.pull_request.labels.*.name, 'run-ut')
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
      GOPRIVATE: github.com/tidbcloud
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false # Use our own cache directly for more effective caching
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: Load Go module cache
        uses: breezewish/gcs-cache/restore@017eacc3417cc8c77f2e7ca1f92cc1be5d54ac1e
        with:
          gcs-bucket: pingcap-dbaas-build_cloudbuild
          path: |
            ~/go/pkg/mod
          key: tidb-cse/ci-build/mod/${{ runner.os }}-${{ runner.arch }}/${{ github.ref_name }}/${{ hashFiles('./go.sum') }}
          restore-keys: |
            tidb-cse/ci-build/mod/${{ runner.os }}-${{ runner.arch }}/${{ github.ref_name }}
            tidb-cse/daily/mod/${{ runner.os }}-${{ runner.arch }}/main-8.5-keyspace/${{ hashFiles('./go.sum') }}
            tidb-cse/daily/mod/${{ runner.os }}-${{ runner.arch }}/main-8.5-keyspace

      - name: Load Go build cache
        uses: breezewish/gcs-cache/restore@017eacc3417cc8c77f2e7ca1f92cc1be5d54ac1e
        with:
          gcs-bucket: pingcap-dbaas-build_cloudbuild
          path: |
            ~/.cache/go-build
          key: tidb-cse/ci-build/build/${{ runner.os }}-${{ runner.arch }}/${{ github.ref_name }}
          restore-keys: |
            tidb-cse/daily/build/${{ runner.os }}-${{ runner.arch }}/main-8.5-keyspace

      - name: make test_part_2
        shell: bash
        run: |
          make test_part_2

  lightning-ut:
    name: Lightning unit test
    runs-on: amd64
    if: contains(github.event.pull_request.labels.*.name, 'run-ut')
    timeout-minutes: 20
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: hub.pingcap.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: run tests
        run: |
          make lightning_unit_test

  cluster-integration-test-1:
    name: Cluster integration test (MySQL Tester)
    runs-on: amd64
    if: contains(github.event.pull_request.labels.*.name, 'run-ut')
    timeout-minutes: 20
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: hub.pingcap.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: run tests
        run: |
          cd tests/clusterintegrationtest
          ./run1.sh

  cluster-integration-test-2:
    name: Cluster integration test (Vector Recall Test)
    runs-on: amd64
    if: contains(github.event.pull_request.labels.*.name, 'run-ut')
    timeout-minutes: 20
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: hub.pingcap.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: run tests
        run: |
          cd tests/clusterintegrationtest
          ./run2.sh

  cluster-integration-test-3:
    name: Cluster integration test (Vector + Upgrade Cluster)
    runs-on: amd64
    if: contains(github.event.pull_request.labels.*.name, 'run-ut')
    timeout-minutes: 20
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: hub.pingcap.net
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: run tests
        run: |
          cd tests/clusterintegrationtest
          ./run3_upgradeTest.sh

  unit-test:
    runs-on: [X64, gcp]
    if: contains(github.event.pull_request.labels.*.name, 'run-ut')
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        worker_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: false
        env:
          GOPRIVATE: "github.com/tidbcloud,github.com/pingcap/dbaas"

      - name: Load Go module cache
        uses: breezewish/gcs-cache/restore@017eacc3417cc8c77f2e7ca1f92cc1be5d54ac1e
        with:
          gcs-bucket: pingcap-dbaas-build_cloudbuild
          path: |
            ~/go/pkg/mod
          key: tidb-cse/ci-build/mod/${{ runner.os }}-${{ runner.arch }}/${{ github.ref_name }}/${{ hashFiles('./go.sum') }}
          restore-keys: |
            tidb-cse/ci-build/mod/${{ runner.os }}-${{ runner.arch }}/${{ github.ref_name }}
            tidb-cse/daily/mod/${{ runner.os }}-${{ runner.arch }}/main-8.5-keyspace/${{ hashFiles('./go.sum') }}
            tidb-cse/daily/mod/${{ runner.os }}-${{ runner.arch }}/main-8.5-keyspace

      - name: Load Go build cache
        uses: breezewish/gcs-cache/restore@017eacc3417cc8c77f2e7ca1f92cc1be5d54ac1e
        with:
          gcs-bucket: pingcap-dbaas-build_cloudbuild
          path: |
            ~/.cache/go-build
          key: tidb-cse/ci-build/build/${{ runner.os }}-${{ runner.arch }}/${{ github.ref_name }}
          restore-keys: |
            tidb-cse/daily/build/${{ runner.os }}-${{ runner.arch }}/main-8.5-keyspace

      - name: make ut-test
        env:
          WORKER_ID: ${{ matrix.worker_id }}
          WORKER_COUNT: 12
          TZ: Asia/Shanghai
        run: |
          make ci-test-job JOB_COUNT=$(($WORKER_COUNT)) JOB_INDEX=$WORKER_ID

  check-test-result:
    runs-on: x64
    if: always()
    needs:
      [
        "test-part-1",
        "test-part-2",
        "unit-test",
        "lightning-ut",
        "cluster-integration-test-1",
        "cluster-integration-test-2",
        "cluster-integration-test-3",
      ]
    steps:
      - run: |
          part_1_result="${{ needs.test-part-1.result }}"
          part_2_result="${{ needs.test-part-2.result }}"
          unit_test_result="${{ needs.unit-test.result }}"
          lightning_ut_result="${{ needs.lightning-ut.result }}"
          cluster_it1_result="${{ needs.cluster-integration-test-1.result }}"
          cluster_it2_result="${{ needs.cluster-integration-test-2.result }}"
          declare -a results=($part_1_result $part_2_result $unit_test_result $cluster_it1_result $cluster_it2_result $cluster_it3_result $lightning_ut_result)
          for result in "${results[@]}"; do
            if [[ "$result" != "success" ]]; then
              exit 1
            fi
          done
